version: '3'

services:
  main-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    command: "npm run start:dev"
    