"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
var react_1 = require("@emotion/react");
var globalStyles = (0, react_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  html,\n  body,\n  h1,\n  h2,\n  h3,\n  h4,\n  h5,\n  input,\n  textarea {\n    padding: 0;\n    margin: 0;\n    word-break: keep-all;\n    text-rendering: optimizeLegibility;\n    -webkit-font-smoothing: antialiased;\n    word-wrap: break-word;\n    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,\n      Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;\n  }\n\n  * {\n    box-sizing: border-box;\n  }\n\n  a {\n    color: inherit;\n    text-decoration: none;\n  }\n\n  button {\n    background: transparent;\n    border: none;\n    box-shadow: none;\n    padding: 0;\n    cursor: pointer;\n\n    &:disabled {\n      cursor: not-allowed;\n      pointer-events: none;\n      filter: brightness(90%);\n      opacity: 0.6;\n    }\n  }\n\n  input[type=\"radio\"],\n  input[type=\"checkbox\"],\n  .input-label {\n    cursor: pointer;\n  }\n"], ["\n  html,\n  body,\n  h1,\n  h2,\n  h3,\n  h4,\n  h5,\n  input,\n  textarea {\n    padding: 0;\n    margin: 0;\n    word-break: keep-all;\n    text-rendering: optimizeLegibility;\n    -webkit-font-smoothing: antialiased;\n    word-wrap: break-word;\n    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,\n      Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;\n  }\n\n  * {\n    box-sizing: border-box;\n  }\n\n  a {\n    color: inherit;\n    text-decoration: none;\n  }\n\n  button {\n    background: transparent;\n    border: none;\n    box-shadow: none;\n    padding: 0;\n    cursor: pointer;\n\n    &:disabled {\n      cursor: not-allowed;\n      pointer-events: none;\n      filter: brightness(90%);\n      opacity: 0.6;\n    }\n  }\n\n  input[type=\"radio\"],\n  input[type=\"checkbox\"],\n  .input-label {\n    cursor: pointer;\n  }\n"])));
exports["default"] = globalStyles;
var templateObject_1;
